steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cognitosparks', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cognitosparks']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cognitosparks'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cognitosparks'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - >-
        SECRET_KEY=${_SECRET_KEY},
        MS_TENANT_ID=${_MS_TENANT_ID},
        MS_CLIENT_ID=${_MS_CLIENT_ID},
        MS_CLIENT_SECRET=${_MS_CLIENT_SECRET},
        MS_LICENSED_USER=${_MS_LICENSED_USER},
        DEBUG=False

substitutions:
  _SECRET_KEY: ${_SECRET_KEY}
  _MS_TENANT_ID: ${_MS_TENANT_ID}
  _MS_CLIENT_ID: ${_MS_CLIENT_ID}
  _MS_CLIENT_SECRET: ${_MS_CLIENT_SECRET}
  _MS_LICENSED_USER: ${_MS_LICENSED_USER}

images:
  - 'gcr.io/$PROJECT_ID/cognitosparks'
