steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
      - "."

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google-cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "SECRET_KEY=${_SECRET_KEY}"
      - "--set-env-vars"
      - "DATABASE_URL=${_DATABASE_URL}"
      - "--set-env-vars"
      - "DEBUG=0"
      - "--set-env-vars"
      - "ALLOWED_HOSTS=${_SERVICE_NAME}.run.app"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--port"
      - "8080"

# Substitutions
substitutions:
  _SERVICE_NAME: cognitosparks  # Default service name, can be overridden in trigger
  _SECRET_KEY: ""              # Set this in Cloud Build trigger
  _DATABASE_URL: ""            # Set this in Cloud Build trigger

# Configure timeout
timeout: "1800s"

# Images to store in Container Registry
images:
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"

# Configure available secrets
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/django_secret_key/versions/latest
      env: '_SECRET_KEY'
    - versionName: projects/$PROJECT_ID/secrets/database_url/versions/latest
      env: '_DATABASE_URL'

# Only trigger builds on main branch
options:
  logging: CLOUD_LOGGING_ONLY

# Tags for the build
tags:
  - digital-twins
  - production
