steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
      - "."

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google-cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "^##^SECRET_KEY=${_SECRET_KEY},DATABASE_URL=${_DATABASE_URL},DEBUG=0,ALLOWED_HOSTS=${_SERVICE_NAME}.run.app,EMAIL_HOST_USER=${_EMAIL_HOST_USER},EMAIL_HOST_PASSWORD=${_EMAIL_HOST_PASSWORD}"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--port"
      - "8080"
      - "--timeout"
      - "300"
      - "--execution-environment"
      - "gen2"
      - "--health-checks"
      - "enabled"
      - "--health-check-timeout"
      - "300s"

# Substitutions
substitutions:
  _SERVICE_NAME: cognitosparks  # Default service name
  _SECRET_KEY: ""              # Set this in Cloud Build trigger
  _DATABASE_URL: ""            # Set this in Cloud Build trigger

# Configure timeout
timeout: "1800s"

# Images to store in Container Registry
images:
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"

# Configure available secrets
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/django_secret_key/versions/latest
      env: '_SECRET_KEY'
    - versionName: projects/$PROJECT_ID/secrets/database_url/versions/latest
      env: '_DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/email_host_user/versions/latest
      env: '_EMAIL_HOST_USER'
    - versionName: projects/$PROJECT_ID/secrets/email_host_password/versions/latest
      env: '_EMAIL_HOST_PASSWORD'

# Only trigger builds on main branch
options:
  logging: CLOUD_LOGGING_ONLY

# Tags for the build
tags:
  - cognitosparks
  - production
