steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cognitosparks', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cognitosparks']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cognitosparks'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cognitosparks'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=DATABASE_URL=${_DATABASE_URL}'
      - '--set-env-vars=SECRET_KEY=${_SECRET_KEY}'
      - '--set-env-vars=EMAIL_HOST_PASSWORD=${_EMAIL_HOST_PASSWORD}'
      - '--set-env-vars=EMAIL_HOST_USER=${_EMAIL_HOST_USER}'

substitutions:
  _DATABASE_URL: ${_DATABASE_URL}
  _SECRET_KEY: ${_SECRET_KEY}
  _EMAIL_HOST_PASSWORD: ${_EMAIL_HOST_PASSWORD}
  _EMAIL_HOST_USER: ${_EMAIL_HOST_USER}

images:
  - 'gcr.io/$PROJECT_ID/cognitosparks'
