steps:
  # Build the container image
  - name: "docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME"
      - "."

  # Push the container image to Artifact Registry
  - name: "docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME"
      - "--region=$_REGION"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--set-env-vars=SECRET_KEY=${_SECRET_KEY},DATABASE_URL=${_DATABASE_URL},DEBUG=1,ALLOWED_HOSTS=${_SERVICE_NAME}.run.app,EMAIL_HOST_USER=${_EMAIL_HOST_USER},EMAIL_HOST_PASSWORD=${_EMAIL_HOST_PASSWORD},DEFAULT_FROM_EMAIL=${_EMAIL_HOST_USER},CONTACT_EMAIL=${_EMAIL_HOST_USER}"

substitutions:
  _SERVICE_NAME: cognitosparks
  _SECRET_KEY: ""
  _DATABASE_URL: ""
  _REGION: "us-central1"

options:
  logging: CLOUD_LOGGING_ONLY
