name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: stoked-woods-432618-g7
  SERVICE_NAME: cognitosparks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Get Current Static Version
      id: get_version
      run: |
        echo "STATIC_VERSION=$(date +%s)" >> $GITHUB_ENV

    - name: Build and Deploy
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        MS_TENANT_ID: ${{ secrets.MS_TENANT_ID }}
        MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
        MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
        MS_LICENSED_USER: ${{ secrets.MS_LICENSED_USER }}
      run: |
        echo "Deploying with Microsoft Graph API configuration and Static Version: $STATIC_VERSION"
        
        gcloud builds submit \
          --substitutions="_SECRET_KEY=$SECRET_KEY,_MS_TENANT_ID=$MS_TENANT_ID,_MS_CLIENT_ID=$MS_CLIENT_ID,_MS_CLIENT_SECRET=$MS_CLIENT_SECRET,_MS_LICENSED_USER=$MS_LICENSED_USER,_STATIC_VERSION=$STATIC_VERSION" \
          --verbosity=debug

    - name: Display build logs
      run: |
        BUILD_ID=$(gcloud builds list --format='value(id)' --limit=1)
        gcloud builds log $BUILD_ID
